---
version: "3.9"
services:
  db:
    extends:
      file: .docker/common.yml
      service: db
    volumes:
      - ./.docker/db/pgcrypto.sql:/docker-entrypoint-initdb.d/10-pgcrypto.sql
      - db-data:/var/lib/postgresql/data

  adminer:
    container_name: metis-adminer
    depends_on: ["db"]
    image: docker.io/library/adminer:4
    ports:
      - "10003:8080"

  metis-backend:
    extends:
      file: .docker/common.yml
      service: metis-backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .docker/s6-rc.d:/etc/s6-overlay/s6-rc.d
      - .:/app
      - metis-backend-home:/root
      - metis-data:/data
      - yanode-pubkeys:/yanode-put-pubkey-here

  metis-bff:
    extends:
      file: .docker/common.yml
      service: metis-bff
    build:
      args:
        - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
      metis-backend:
        condition: service_healthy
    volumes:
      - ../metis-bff:/app
    entrypoint: "npm run dev"

  metis-gui:
    extends:
      file: .docker/common.yml
      service: metis-gui
    depends_on: ["metis-bff"]
    build:
      context: ../metis-gui

  yanode:
    extends:
      file: .docker/common.yml
      service: yanode
    volumes:
      - yanode-host-keys:/config/ssh_host_keys
      - yanode-pubkeys:/pubkeys
      - yanode-data:/config/data

volumes:
  db-data: {}
  rmq-data: {}
  metis-backend-home: {}
  metis-data: {}
  yanode-data: {}
  yanode-host-keys: {}
  yanode-pubkeys: {}
